name: 'Mosquitto MQTT Broker in GitHub Actions'
description: 'Start a Mosquitto message broker as Docker container'

branding:
  icon: 'message-square'
  color: 'red'

inputs:
  version:
    description: 'Mosquitto version to use'
    required: false
    default: 'latest'
  ports:
    description: 'Port mappings in a [host]:[container] format, delimited by spaces (example: "1883:1883 8883:8883")'
    required: false
    default: '1883:1883'
  certificates:
    description: 'Absolute path to a directory containing certificate files which can be referenced in the config (the folder is mounted under `/mosquitto-certs`)'
    required: false
    default: ''
  anonymous:
    description: 'Allow anonymous connections.'
    required: false
    default: false
  config_dir:
    description: 'Absolute path to the config dir containing the configuration file to use'
    required: false
    default: ''
  password-file:
    description: 'Absolute path to the mosquitto.passwd password file to use'
    required: false
    default: ''
  container-name:
    description: 'The name of the spawned Docker container (can be used as hostname when accessed from other containers)'
    required: false
    default: 'mosquitto'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.ports }}
    - ${{ inputs.anonymous }}
    - ${{ inputs.certificates }}
    - ${{ inputs.config_dir }}
    - ${{ inputs.password-file }}
    - ${{ inputs.container-name }}
