name: Start Mosquitto Broker

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-broker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.5, 1.6, 2.0, latest]

    name: Start Mosquitto Broker [${{ matrix.version }}]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Mosquitto Broker
        uses: ./
        with:
          version: ${{ matrix.version }}
